# Generated by Django 3.2.12 on 2022-04-02 10:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BTCName',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('tweeted_at', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'BTC Names',
            },
        ),
        migrations.CreateModel(
            name='Leaderboard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('twitter_id', models.CharField(blank=True, max_length=100, null=True)),
                ('twitter_name', models.CharField(blank=True, max_length=100, null=True)),
                ('twitter_username', models.CharField(blank=True, max_length=100, null=True)),
                ('twitter_follower_count', models.BigIntegerField(blank=True, null=True)),
                ('is_updated', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Mentions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'Mentions',
            },
        ),
        migrations.CreateModel(
            name='StacksInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bns_sync_height', models.BigIntegerField()),
            ],
            options={
                'verbose_name_plural': 'Stacks Info',
            },
        ),
    ]
